### ISSUE TITLE
Confusing output of ROOT.TTree.statVar method

### ISSUE THREAD

**Issue by aleksha** [OstapHEP/ostap#15]
Output prints " ... mean = XXX +- YYY ...", which is a bit confusing, as YYY is an individual uncertainty of single entry, but not an uncertainty of the mean, which is also random value. Better switch to ""...mean=XXX rms=YYY...".

In principle, estimates of uncertainties for mean and rms random valuers (under the Gaussian hypothesis ) are also worth to be printed.

Let me alsothsnk authors for the incredible tool!!

**Comment by VanyaBelyaev** [comment]
the print always will be a bit misleading - it is almost   unavoidable.  but the object itself has all the methods , like `mean`, `rms`, etc. that are fine  and one can  get  their corresponding uncertainties.

**Comment by VanyaBelyaev** [comment]
The output for `Ostap::StatEntity` and `Ostap:WStatEntity` classes is fixed in `v1.5.0.1` 
New format is   `mean/rms=XXX/YYY`
