### ISSUE TITLE
Error with ROOT.TMinuit 

### ISSUE THREAD

**Issue by aleksha** [OstapHEP/ostap#9]
Seems TMinuit works not correctly as it fails if one tries to follow examples.  (Ostap: 1.4.5.0, Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) ) 

In [1]: m = ROOT.TMinuit(9)                                                                                                                                                         
In [2]: help(m)                                                                                                                                                                     
In [3]: m.addPar ( 'ququ' , 10 , 0.1 )                                                                                                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/adzyuba/miniconda3/envs/ostap-env/bin/ostap in <module>
----> 1 m.addPar ( 'ququ' , 10 , 0.1 )

/home/adzyuba/miniconda3/envs/ostap-env/lib/python3.8/site-packages/ostap/fitting/minuit.py in _mn_add_par_(self, name, start, step, low, high)
    225     ipar    = len ( self )
    226     ierr    = ROOT.Long   ( 0 )
--> 227     self.mnparm ( ipar , name ,  start , step , low , high , ierr )
    228     #
    229     return ierr

TypeError: void TMinuit::mnparm(int k, TString cnamj, double uk, double wk, double a, double b, int& ierflg) =>
    could not convert argument 7 (use ctypes.c_int for pass-by-ref of ints)

**Comment by VanyaBelyaev** [comment]
Dear Alexey,
thank you for reporting the problem. Do you have some (relatively short) complete example that I can use as a test  suit?

**Comment by aleksha** [comment]
I do not have an example as my initaial attempt was to create one, but for this i have to understand methods (ostap wrappers). It failed in interactive regime right after trying to call addPar method.

**Comment by VanyaBelyaev** [comment]
I've put couple of minor fixes and added a test/example `test_fitting_minuit`
